### ISSUE TITLE
Issues With Assignment

### ISSUE THREAD

**Issue by Panda64** [soggybag/learn-markup-level-2#3]
1. For some reason, Challenge 4 and its solution is under the notes tab, not with the other 3 challenges.
<img width="294" alt="Screen Shot 2020-08-28 at 3 12 50 PM" src="https://user-images.githubusercontent.com/36112163/91619112-0a1c6300-e941-11ea-9328-889662818ce7.png">

2. The following screenshot is from the challenge 2 solution
<img width="547" alt="Screen Shot 2020-08-28 at 3 14 39 PM" src="https://user-images.githubusercontent.com/36112163/91619189-418b0f80-e941-11ea-99c4-0ddcbb644d4f.png">

The link on line 55 is different in the assignment version. At least for me, this prevented the finished product to work unless this link was changed to the one on the solution file.

3. The following screenshot is from the challenge 3 assignment 
<img width="610" alt="Screen Shot 2020-08-28 at 3 18 09 PM" src="https://user-images.githubusercontent.com/36112163/91619368-bcecc100-e941-11ea-9cc8-169e2771b091.png">

The instructions in the assignment file or the README did not say that there had to be id="giphy-search" on line 13, when this needs to be there in order for the final product to work.

**Comment by soggybag** [comment]
You’re too clever for me! I had made this one but later decided to take it out. I think I’m going to use it for a later project. I hadn’t bothered to re number the other files.

**Comment by soggybag** [comment]
swapi changed their url to https. I must have missed updating the unfinished version of the file. 

Stretch challenge! 

- fork this repo
- change the url
-  make a pull request
